name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout submodules
      # Initialise submodules
      run: git submodule update --init --recursive
      
    - name: Install SFML dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfreetype6-dev libx11-dev libxrandr-dev libudev-dev libopengl0-mesa-dev libflac-dev libogg-dev libvorbis-dev libopenal-dev libpthread-stubs0-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

