name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login --username joelbeedle --password ${{ secrets.GH_PAT }} ghcr.io
        docker build . --file Dockerfile --tag ghcr.io/joelbeedle/salsa:latest
        docker push ghcr.io/joelbeedle/salsa:latest
